services:

  nginx:
    image: nginx:1.14.2-alpine
    ports:
      - ${BIND_HOST:-127.8.0.1}:${BIND_PORT:-8000}:8000
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/app/:ro

  laravel:
    build:
      context: ../layers
      dockerfile: ./Dockerfile
    working_dir: /app
    environment:
      PHP_FPM_USER: www-data
      PHP_FPM_GROUP: www-data
      APP_URL: http://${BIND_HOST:-127.8.0.1}:${BIND_PORT:-8000}
    volumes:
      - ./conf/php-fpm-www.conf:/usr/local/etc/php-fpm.d/zz-www.conf:ro
      - ./src:/app/:rw
    tmpfs:
      - /app/storage/logs:mode=0777,uid=82,gid=82
      - /app/bootstrap/cache:mode=0777,uid=82,gid=82
      - /app/storage/framework/views/:mode=0777,uid=82,gid=82
      - /app/storage/framework/cache/:mode=0777,uid=82,gid=82
      - /app/storage/framework/sessions/:mode=0777,uid=82,gid=82

  node:
    ports:
      - ${BIND_HOST:-127.8.0.1}:5173:5173
    image: node:20.14.0-alpine3.19
    entrypoint: sh -c 'npm i && npm run dev'
    working_dir: /app
    environment:
      VITE_HMR_HOST: ${BIND_HOST:-127.8.0.1}
    volumes:
      - ./src:/app/:rw
